#!/opt/homebrew/bin/expect -f

set CLEMSON_USERNAME [lindex $argv 0]
set CLEMSON_PASSWORD [lindex $argv 1]

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout -1
spawn cuvpn-interactive $CLEMSON_USERNAME
match_max 100000
expect "Password:"
send -- "$CLEMSON_PASSWORD\r"
expect "Password:"
send -- "push\r"
expect eof
