#!/usr/bin/env zsh
filedir=~/Pictures/Screenshots/
filename=$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)
screencapture -i $filedir$filename.png
if [ -f $filedir$filename.png ]
then
	# Screenshots will be compressed before upload; the local copy will still be full quality.
	pngquant --quality=0-80 -s7 $filedir$filename.png --ext _compressed.png 
	gsutil cp $filedir${filename}_compressed.png gs://i.quartzic.co/$filename
	printf https://i.quartzic.co/$filename | pbcopy
	afplay /System/Library/Sounds/Glass.aiff
	rm $filedir${filename}_compressed.png
fi
