#!/usr/bin/env zsh
filedir=~/Pictures/Screenshots/
filename=$(cat /dev/urandom | env LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)
screencapture -i $filedir$filename.png
if [ -f $filedir$filename.png ]
then
	# Screenshots will be compressed before upload; the local copy will still be full quality.
	convert $filedir$filename.png -quality 85% "$filedir${filename}.jpg"
	rm $filedir$filename.png
	gsutil cp $filedir${filename}.jpg gs://i.quartzic.co/$filename
	printf https://i.quartzic.co/$filename | pbcopy
	afplay /System/Library/Sounds/Glass.aiff
fi
